/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mamun_CSE
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnin = new javax.swing.JButton();
        btndlt = new javax.swing.JButton();
        btnupd = new javax.swing.JButton();
        btnsrc = new javax.swing.JButton();
        btne = new javax.swing.JButton();
        btnshow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("     TITLE");

        btnin.setBackground(new java.awt.Color(153, 153, 153));
        btnin.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnin.setForeground(new java.awt.Color(153, 153, 153));
        btnin.setText("INSERT");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        btndlt.setBackground(new java.awt.Color(153, 153, 153));
        btndlt.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btndlt.setForeground(new java.awt.Color(153, 153, 153));
        btndlt.setText("DELETE");
        btndlt.setActionCommand("");
        btndlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndltActionPerformed(evt);
            }
        });

        btnupd.setBackground(new java.awt.Color(153, 153, 153));
        btnupd.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnupd.setForeground(new java.awt.Color(153, 153, 153));
        btnupd.setText("UPDATE");
        btnupd.setActionCommand("");
        btnupd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdActionPerformed(evt);
            }
        });

        btnsrc.setBackground(new java.awt.Color(153, 153, 153));
        btnsrc.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnsrc.setForeground(new java.awt.Color(153, 153, 153));
        btnsrc.setText("SEARCH");
        btnsrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrcActionPerformed(evt);
            }
        });

        btne.setBackground(new java.awt.Color(153, 153, 153));
        btne.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btne.setForeground(new java.awt.Color(153, 153, 153));
        btne.setText("EXIT");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });

        btnshow.setBackground(new java.awt.Color(153, 153, 153));
        btnshow.setFont(new java.awt.Font("Segoe Script", 2, 24)); // NOI18N
        btnshow.setForeground(new java.awt.Color(153, 153, 153));
        btnshow.setText("SHOW");
        btnshow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndlt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnupd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsrc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsrc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnupd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btndlt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnshow, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btne, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndltActionPerformed
        
        this.dispose();
            String oldName = JOptionPane.showInputDialog("Enter Old Book Name");
           
             Connection con = null;
             Statement prst = null;
             ResultSet rs=null;
        
                   try{
                   Class.forName("com.mysql.jdbc.Driver");
                   con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Library" ,"root" , "1234") ;
                   String que = "delete from info where bookname='"+oldName+"'";
                   prst = con.createStatement();
                   prst.executeUpdate(que);
                   JOptionPane.showMessageDialog(null, "Data Deleded");
                   new Table().setVisible(true);
                 
            }
            catch(Exception ee){
                System.out.println(ee.getMessage());
            }
        finally{
                if(con!=null){
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(prst!=null){
                    try {
                        prst.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
            
            
            
         
              
    }//GEN-LAST:event_btndltActionPerformed

    private void btnupdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdActionPerformed
           
         this.dispose();
        String oldName = JOptionPane.showInputDialog("Enter Old Book Name");
            String newName = JOptionPane.showInputDialog("Enter New Name for Update");
            
             Connection con = null;
             Statement prst = null;
             ResultSet r=null;
        
                   try{
                   Class.forName("com.mysql.jdbc.Driver");
                   con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Library" ,"root" , "1234") ;
                   String que = "update info set bookname = '"+newName+"' where bookname = '"+oldName+"'";
                   prst = con.createStatement();
                   prst.executeUpdate(que);
                   JOptionPane.showMessageDialog(null, "DATA UPDATED");
                   new Table().setVisible(true);
                 
            }
            catch(Exception ee){
                System.out.println(ee.getMessage());
            }
        finally{
                if(con!=null){
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(prst!=null){
                    try {
                        prst.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
            
            
            
            
    }//GEN-LAST:event_btnupdActionPerformed

    private void btnsrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrcActionPerformed
            this.dispose();
            String borrowerr = JOptionPane.showInputDialog("Enter Borrower Name : ");
           
            
             Connection con = null;
             Statement st = null;
             ResultSet rs=null;
           
        
                   try{
                   Class.forName("com.mysql.jdbc.Driver");
                   con =DriverManager.getConnection("jdbc:mysql://localhost:3306/Library" ,"root" , "1234") ;
                   String que = "select * from info where borrower='"+borrowerr+"' ";
                    st = con.createStatement();
                    rs= st.executeQuery(que);  
                    while(rs.next()){
                    JOptionPane.showMessageDialog(null, "Book Name : " + rs.getString(1) + " Qunatity = " + rs.getInt(4));
                    }
                    this.setVisible(true);
                 
            }
            catch(Exception ee){
                System.out.println(ee.getMessage());
            }
        finally{
                if(con!=null){
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                else if(st!=null){
                    try {
                        st.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
        }
            
            
            
         
    }//GEN-LAST:event_btnsrcActionPerformed

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
            new InFrame().setVisible(true);
            this.dispose();
                    

    }//GEN-LAST:event_btninActionPerformed

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
            this.dispose();
    }//GEN-LAST:event_btneActionPerformed

    private void btnshowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowActionPerformed
                this.dispose();
                new Table().setVisible(true);
               
                        
    }//GEN-LAST:event_btnshowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndlt;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnshow;
    private javax.swing.JButton btnsrc;
    private javax.swing.JButton btnupd;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
